name: conversation-manager
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  # Core Python
  - python=3.11
  
  # Core Flask Backend
  - flask>=2.3.0
  - flask-cors>=4.0.0
  - requests>=2.31.0
  
  # Data and Configuration
  - toml>=0.10.2
  - pandas>=1.5.0
  - numpy>=1.24.0
  
  # Streamlit Interface
  - streamlit>=1.28.0
  
  # Database
  - duckdb>=0.9.0
  
  # Vector Databases
  - chromadb>=0.4.0
  # - faiss>=1.7.0  # Uncomment if using FAISS
  
  # Machine Learning and AI
  - openai>=1.0.0
  - scikit-learn>=1.3.0
  
  # Document Processing
  - pillow>=9.0.0
  - beautifulsoup4>=4.12.0
  
  # Utilities
  - pathlib2
  - python-dateutil
  - pytz
  - tqdm
  
  # Development and Testing
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0
  - ipython>=8.0.0
  - jupyter>=1.0.0
  
  # Visualization (optional)
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  - pip
  - pip:
    # Document Processing with Docling (not available on conda)
    - docling>=1.0.0
    
    # REDCap Integration (not available on conda)
    - pycap>=2.5.0
    
    # Additional pip-only packages
    - python-multipart>=0.0.6  # For file uploads in FastAPI/Flask
    
    # Session Data Management
    - redis>=5.0.0  # For session management and caching

    # utilities
    - uuid
    # Optional: OCR capabilities
    # - pytesseract>=0.3.0
    
    # Optional: Advanced NLP
    # - transformers>=4.21.0
    # - sentence-transformers>=2.2.0


# To create environment:
# conda env create -f environment.yml

# To activate:
# conda activate conversation-manager

# To update the environment with changes from environment.yml:
# conda env update --file environment.yml --name conversation-manager

# To stop:
# conda deactivate

# Delete the environment 
# conda remove --name conversation-manager --all